apiVersion: v1
kind: PersistentVolume
metadata:
  name: library-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/library # Path on the host where the volume will be mounted
