apiVersion: v1
kind: Service
metadata:
  name: library-management-service
  labels:
    app: library-management
spec:
  type: NodePort
  selector:
    app: library-management
  ports:
    - protocol: TCP
      port: 80         # Port exposed by the service
      targetPort: 5000 # Port on the container
      nodePort: 30007  # Port on the node
