apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-prometheus-alertmanager-pv
  namespace: monitoring
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/alertmanager
  storageClassName: manual
