apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-management
  template:
    metadata:
      labels:
        app: library-management
    spec:
      containers:
        - name: library-management-container
          image: ahmedyehia32/library-system-final
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
            - containerPort: 8000  # Expose the metrics port
