apiVersion: v1
kind: Service
metadata:
  name: library-management-service
spec:
  selector:
    app: library-management
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer